server:
  port: 8080
feign:
  compression:
    request:
      enabled: true
      mime-types: text/mxl,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
      
      
